services:
  assetto-multiserver:
    image: ubuntu:22.04
    container_name: acsm
    restart: always
    stop_signal: SIGINT
    working_dir: /home/assetto/server-manager
    entrypoint: ["/bin/sh", "/opt/infra/entrypoint.sh"]

    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.acsm.loadbalancer.server.port=8772"

      - "traefik.http.routers.race.rule=${ACSM_RULE}"
      - "traefik.http.routers.race.entrypoints=websecure"
      - "traefik.http.routers.race.tls=true"
      - "traefik.http.routers.race.tls.certresolver=leresolver"
      - "traefik.http.routers.race.service=acsm"

      - "traefik.http.routers.race-http.rule=${ACSM_RULE}"
      - "traefik.http.routers.race-http.entrypoints=web"
      - "traefik.http.routers.race-http.middlewares=redirect-to-https@file"

      - "traefik.http.middlewares.hsts.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.hsts.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.hsts.headers.stsPreload=true"
      - "traefik.http.routers.race.middlewares=hsts"

    volumes:
      - /opt/acsm-bins:/opt/acsm-repo:ro
      - /opt/acsm-secrets/ACSM.License:/ACSM.License:ro
      - ./infra/entrypoint.sh:/opt/infra/entrypoint.sh:ro
      - ./my-config/config.yml:/home/assetto/server-manager/config.yml:ro
      - ./my-config/servers.yml:/home/assetto/server-manager/servers.yml:ro
      - assetto_data:/home/assetto/server-manager/assetto
      - servers_data:/home/assetto/server-manager/servers

    ports:
      - "9601-9610:9601-9610"
      - "9601-9610:9601-9610/udp"
      - "8801-8810:8801-8810"

networks:
  proxy:
    external: true
    name: proxy

volumes:
  assetto_data:
  servers_data:
